### DISCUSSION TITLE
基于2.x分支在IDEA启动server找不到注册中心的namespace

### DISCUSSION THREAD

**Discussion by YvCeung** [apache/incubator-seata#6958] [Q&A]
问题：注册到nacos上的namespace和group与我本地配置不相符

背景：基于2.x分支，server端源码IDEA部署，无法识别nacos（2.3版本）注册中心namespace。我在yml文件配置了registry的地址和namespace以及group,如下，但是启动后，nacos上显示的是注册到了默认的空间

其他信息：当我启动的时候，控制台打印的信息可以验证能正确读到nacos上的配置文件，见图三

```yml
  seata:
    registry:
      # support: nacos, eureka, redis, zk, consul, etcd3, sofa
      type: nacos
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: '3688929d-ed43-484d-b01c-1de748697ea4'
      group: 'seata'
      cluster: default
    config:
      # support: nacos, consul, apollo, zk, etcd3
      type: nacos
      nacos:
        server-addr: 127.0.0.1:8848
        namespace: '3688929d-ed43-484d-b01c-1de748697ea4'
        group: 'seata'
        data-id: seataServer.properties
    # store:
      # support: file 、 db 、 redis 、 raft
    #  mode: file
    #  server:
    #    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
```
<img width="916" alt="image" src="https://github.com/user-attachments/assets/81300ef2-aa4f-4947-8372-ed407161f43f">

<img width="1403" alt="image" src="https://github.com/user-attachments/assets/2af2163c-bf53-4b0f-9e85-0872a73ae0bd">
