### ISSUE TITLE
seata server 2.0.0 UI界面登录提示"服务器成功返回请求的数据。" 没有任何反应

### ISSUE THREAD

**Issue by biabiubiu** [apache/incubator-seata#6431]
现象：
![屏幕截图 2024-03-17 173726](https://github.com/apache/incubator-seata/assets/46422666/c6228d32-4ac2-459e-92cc-5d59dc4aa779)
后台没看到明显报错日志
![image](https://github.com/apache/incubator-seata/assets/46422666/e97d36f6-2567-4031-a433-2f55b8ddaf26)

**Comment by liuqiufeng** [comment]
请提供具体操作步骤、参数及环境等信息以便复现。另外能否展开浏览器错误提示看下详细错误信息以及响应内容？

Please provide specific steps, parameters and environment information for reproduction. Also, can you expand the browser error message to see the detailed error message and response content?

**Comment by biabiubiu** [comment]
详细错误信息：去掉附件k8s-master.har.txt 的.txt导入chrome。
[k8s-master.har.txt](https://github.com/apache/incubator-seata/files/14668785/k8s-master.har.txt)
环境信息：
系统：inux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) )
k8s（1 master + 1 node）:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

docker 版本：
![image](https://github.com/apache/incubator-seata/assets/46422666/6e9522f4-4907-4bd0-b5dd-6876fc0448c2)

**Comment by biabiubiu** [comment]
以下是yaml
操作步骤：
kubectl apply -f xxx.yaml ,没有其它操作

```yaml
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: ggs-bs-master
  labels:
    app.kubernetes.io/name: seata-server
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 31091
    - name: http-ui
      protocol: TCP
      port: 7091
      targetPort: 7091
      nodePort: 30091
  selector:
    app.kubernetes.io/name: seata-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: ggs-bs-master
  labels:
    app.kubernetes.io/name: seata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-server
    spec:
      containers:
        - name: seata-server
          image: seataio/seata-server:2.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /seata-server/resources/application.yml
              subPath: application.yml
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: ggs-bs-master
data:
  application.yml: |
    server:
      port: 7091
    spring:
      application:
        name: seata-server
    logging:
      config: classpath:logback-spring.xml
      file:
        path: ${user.home}/logs/seata
      extend:
        logstash-appender:
          destination: 127.0.0.1:4560
        kafka-appender:
          bootstrap-servers: 127.0.0.1:9092
          topic: logback_to_logstash
    console:
      user:
        username: seata
        password: xxxxx
    seata:
      config:
        # support: nacos 、 consul 、 apollo 、 zk  、 etcd3
        type: nacos
        nacos:
          server-addr: nacos-headless:8848
          namespace: seata
          group: xxx
          username: xxx
          password: xxx
          data-id: seata-server.yaml
      registry:
        # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa
        type: nacos
        nacos:
          application: seata-server
          server-addr: nacos-headless:8848
          group: xxxx
          namespace: xxx
          cluster: default
          username: xxx
          password: xxxx
      security:
        secretKey: xxxxxxxxxxxxx
        tokenValidityInMilliseconds: 1800000
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/metadata/v1/**
```

**Comment by liuqiufeng** [comment]
Can you provide a detailed error message from the browser console? Including server-side response information.

**Comment by ptyin** [comment]
I cannot reproduce same error as you did. I tested it using following setups, and it works for me.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: default
  labels:
    app.kubernetes.io/name: seata-server
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 31091
    - name: http-ui
      protocol: TCP
      port: 7091
      targetPort: 7091
      nodePort: 30091
  selector:
    app.kubernetes.io/name: seata-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: default
  labels:
    app.kubernetes.io/name: seata-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-server
    spec:
      containers:
        - name: seata-server
          image: seataio/seata-server:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
```

<img width="634" alt="image" src="https://github.com/apache/incubator-seata/assets/32592585/97a9ae4d-171f-40ab-bb61-7d64c718c426">
