### ISSUE TITLE
seata1.3.0自定义异常被全局异常捕获后异常信息变为Runtime Excetion

### ISSUE THREAD

**Issue by zhanxuewei** [apache/incubator-seata#6470]
背景：
我使用的是seata1.3.0版本，现在有两个微服务：订单微服务OrderServer、库存微服务StockServer,在创建订单过程中，订单服务会通过openfeign远程调用库存服务进行扣减库存。我手动在库存服务里面抛出了一个自定义异常（我的全局异常捕获类中有捕获自定义异常）。
问题：
现在我手动抛出的这个自定义异常，被全局异常捕获到，但是捕获到的异常变成了RuntimeExcetion（我期望捕获到的是我自定义的异常，cdoe和message应该是我自定义的信息），结果丢失了异常信息。
ps：虽然抛出了RuntimeException，我通过excetion的case信息可以拿到预期的message，但是code却获取不到。

**Comment by zhanxuewei** [comment]
// 订单服务局部代码
 log.info("发起OPENFEIGN远程调用【扣减库存】,【参数】stockDTOList：{}",JSON.toJSONString(stockDTOList));
        ApiResult<ResultCode> stockReduceApiResult = this.stockServerFeignApi.reduce(stockDTOList);
        log.info("OPENFEIGN远程调用完成，【结果】：{}", JSON.toJSONString(stockReduceApiResult));
        if (ResultCode.SUCCESS.getCode() != stockReduceApiResult.getCode()) {
            throw new BizException(stockReduceApiResult.getMessage(), stockReduceApiResult.getCode());
        }

**Comment by zhanxuewei** [comment]
// 库存服务
    @GlobalTransactional
    @Override
    public void stockChange(List<StockDTO> stockDTOList, Boolean flag) {
        List<StockEntity> list = new ArrayList<>();
        for (StockDTO stockDTO : stockDTOList) {
            LambdaQueryWrapper<StockEntity> wrapper = new LambdaQueryWrapper<>();
            wrapper.eq(StockEntity::getProductId, stockDTO.getProductId());
            StockEntity stockEntity = super.getOne(wrapper);
            if (Objects.isNull(stockEntity)) {
                throw new BizException(ResultCode.PRODUCT_NOT_FOUND);
            }
            Integer stock = stockEntity.getStock();
            Integer resultStock = flag ? stock + stockDTO.getNumber() : stock - stockDTO.getNumber();
            stockEntity.setStock(resultStock);
            list.add(stockEntity);
        }
        if (CollUtil.isNotEmpty(list)) {
            super.saveOrUpdateBatch(list);
        }

        throw new BizException(ResultCode.FILE_SIZE_TOO_BIG_ERROR);

    }

**Comment by zhanxuewei** [comment]
`        log.info("发起OPENFEIGN远程调用【扣减库存】,【参数】stockDTOList：{}",JSON.toJSONString(stockDTOList));
        ApiResult<ResultCode> stockReduceApiResult = this.stockServerFeignApi.reduce(stockDTOList);
        log.info("OPENFEIGN远程调用完成，【结果】：{}", JSON.toJSONString(stockReduceApiResult));
        if (ResultCode.SUCCESS.getCode() != stockReduceApiResult.getCode()) {
            throw new BizException(stockReduceApiResult.getMessage(), stockReduceApiResult.getCode());
        }`

**Comment by zhanxuewei** [comment]
`
        log.info("发起OPENFEIGN远程调用【扣减库存】,【参数】stockDTOList：{}",JSON.toJSONString(stockDTOList));
        ApiResult<ResultCode> stockReduceApiResult = this.stockServerFeignApi.reduce(stockDTOList);
        log.info("OPENFEIGN远程调用完成，【结果】：{}", JSON.toJSONString(stockReduceApiResult));
        if (ResultCode.SUCCESS.getCode() != stockReduceApiResult.getCode()) {
            throw new BizException(stockReduceApiResult.getMessage(), stockReduceApiResult.getCode());
        }

`

**Comment by zhanxuewei** [comment]
`
    @GlobalTransactional
    @Override
    public void stockChange(List<StockDTO> stockDTOList, Boolean flag) {
        List<StockEntity> list = new ArrayList<>();
        for (StockDTO stockDTO : stockDTOList) {
            LambdaQueryWrapper<StockEntity> wrapper = new LambdaQueryWrapper<>();
            wrapper.eq(StockEntity::getProductId, stockDTO.getProductId());
            StockEntity stockEntity = super.getOne(wrapper);
            if (Objects.isNull(stockEntity)) {
                throw new BizException(ResultCode.PRODUCT_NOT_FOUND);
            }
            Integer stock = stockEntity.getStock();
            Integer resultStock = flag ? stock + stockDTO.getNumber() : stock - stockDTO.getNumber();
            stockEntity.setStock(resultStock);
            list.add(stockEntity);
        }
        if (CollUtil.isNotEmpty(list)) {
            super.saveOrUpdateBatch(list);
        }

        **throw new BizException(ResultCode.FILE_SIZE_TOO_BIG_ERROR);**

    }

`

**Comment by zhanxuewei** [comment]
```java
    @GlobalTransactional
    @Override
    public void stockChange(List<StockDTO> stockDTOList, Boolean flag) {
        List<StockEntity> list = new ArrayList<>();
        for (StockDTO stockDTO : stockDTOList) {
            LambdaQueryWrapper<StockEntity> wrapper = new LambdaQueryWrapper<>();
            wrapper.eq(StockEntity::getProductId, stockDTO.getProductId());
            StockEntity stockEntity = super.getOne(wrapper);
            if (Objects.isNull(stockEntity)) {
                throw new BizException(ResultCode.PRODUCT_NOT_FOUND);
            }
            Integer stock = stockEntity.getStock();
            Integer resultStock = flag ? stock + stockDTO.getNumber() : stock - stockDTO.getNumber();
            stockEntity.setStock(resultStock);
            list.add(stockEntity);
        }
        if (CollUtil.isNotEmpty(list)) {
            super.saveOrUpdateBatch(list);
        }

        throw new BizException(ResultCode.FILE_SIZE_TOO_BIG_ERROR);

    }
````

**Comment by zhanxuewei** [comment]
```java
    @ResponseStatus(HttpStatus.OK)
    @ExceptionHandler(value = Exception.class)
    public ApiResult handleException(Exception exception) {
        return ApiResult.failed(ResultCode.FAILED.getCode(), exception.getCause().getMessage());
    }
```

**Comment by zhanxuewei** [comment]
```java
    @ResponseStatus(HttpStatus.OK)
    @ExceptionHandler(BizException.class)
    public ApiResult handleRRException(BizException exception) {
        return ApiResult.failed(exception.getCode(), exception.getMessage());
    }
// 这里的BizException被handleException(Excetion)捕获了
```

**Comment by funky-eyes** [comment]
Only 2.0 is a runtimeException, check for dependency conflicts

**Comment by zhanxuewei** [comment]
thinks for your reply，i will try



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: funkye ***@***.***&gt;
发送时间: 2024年4月7日 22:48
收件人: apache/incubator-seata ***@***.***&gt;
抄送: zhanxuewei ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [apache/incubator-seata] seata1.3.0自定义异常被全局异常捕获后异常信息变为Runtime Excetion (Issue #6470)





 
Only 2.0 is a runtimeException, check for dependency conflicts

**Comment by XieYingFa** [comment]
@funky-eyes 下一个版本会修复此问题么

**Comment by zhanxuewei** [comment]
```xml
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.6.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by zhanxuewei** [comment]
```xml
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.6.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by zhanxuewei** [comment]
```yml
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  #excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: nacos
    nacos:
      namespace: "dev"
      serverAddr: 120.79.12.129:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "zhanxuewei123.."
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 120.79.12.129:8848
      group : "SEATA_GROUP"
      namespace: "dev"
      username: "nacos"
      password: "zhanxuewei123.."
```

**Comment by zhanxuewei** [comment]
```yml
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  #excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: nacos
    nacos:
      namespace: "dev"
      serverAddr: xxxxxxxx:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "xxxxxxxx"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: xxxxxx:8848
      group : "SEATA_GROUP"
      namespace: "dev"
      username: "nacos"
      password: "xxx"

```
