### ISSUE TITLE
建议在application.example.yml文件中加上console.*和security.*配置

### ISSUE THREAD

**Issue by hmj776521114** [apache/incubator-seata#6725]
## Why you need it?
当我下载seata release v2.0后，通常我是把application.yml改为application.yml.bak,  application.example.yml改为application.yml。
但是当我把一些初始配置配置好后启动报错：
> Error creating bean with name 'customUserDetailsServiceImpl': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'console.user.username' 

经过上网查询后了解到需要再配置文件里补充上以下内容：
```yaml

console: 
  user:
    username: seata
    password: seata

seata:
  security:
    secretKey: "seata"
    tokenValidityInMilliseconds: 1000000000

```

## How it could be?
希望在`application.example.yml`配置文件中默认添加上这些内容, 谢谢 !
