### ISSUE TITLE
TCC模式遇到了奇怪的问题：提交重试超时后不会进入回滚流程

### ISSUE THREAD

**Issue by chenbihao** [apache/incubator-seata#6884]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

TCC模式遇到了奇怪的问题，提交重试超时后不会进入回滚流程？可以往哪个方向排查？

### Ⅱ. Describe what happened

写了个使用TCC模式的 SpringCloud 2023 demo，demo是由一个触发的Controller调用本地bean的方法，业务操作是标记删除某条数据，并且为这个表加上了locked字段作为锁定资源，后面附上代码；

发现当commit阶段抛出异常时，无法按照预期流程进行（commit抛出异常应该是触发回滚？）

#### 触发与调整经历

最开始，我是遇到了个空指针异常，是由context.getActionContext抛出来的，排查后发现把@BusinessActionContextParameter写在实现的方法上就解决了

然后我正常测试TCC的流程，往commit流程塞入异常抛出，发现抛出异常时，会无限重试，于是我调整了server配置：

```yml
seata:
  server:
    max-commit-retry-timeout: 5000
    max-rollback-retry-timeout: 8000
    distributedLockExpireTime: 10000
```

然后继续尝试，后面发现每次调用的行为都很奇怪，清空seata server db 的表内容，重启相关服务，然后：

- 第一次请求，debug断点看到，直接跑了Cancel回滚方法
- 第二次请求，debug断点看到，是跑了commit提交方法，经过几次重试后就 “提交重试超时失败”的状态了
- 一致循环下去

![image](https://github.com/user-attachments/assets/d0203ea9-907c-4df9-85b0-2e86e068ec5e)

翻了些文章，看到了 【在 Seata1.5.1 版本中，增加了一张事务控制表，表名是 tcc_fence_log 来解决这个问题】

于是我建了这个表，并且加上注解属性：`useTCCFence = true,`  ，也还是不行，重试超时后也不会进入回滚方法

![image](https://github.com/user-attachments/assets/c2db8fb8-a142-4abe-92d9-e9b2db0cccc2)

可以看出我哪步操作有问题吗？或者可以往哪个方向排查？
