### ISSUE TITLE
Add potential authentication mechanism for port `8091` of Seata Server

### ISSUE THREAD

**Issue by linghengqian** [apache/incubator-seata#6961]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

- I noticed something strange when trying to improve the unit test execution time of https://github.com/apache/shardingsphere/blob/5.5.1/test/native/src/test/java/org/apache/shardingsphere/test/natived/jdbc/transactions/base/SeataTest.java . 
- For the `7091` port of Seata Server, there is an authentication mechanism that requires users to log in with the account of `seata` and the password of `seata`.
- But for the `8091` port of Seata Server, it seems that there is no authentication mechanism. Any Seata Client can directly connect to the `8091` port of Seata Server. This does not seem to change anything because Seata Server switches to Nacos's configuration center or registration center. After Seata Client connects to Nacos Server, it still needs to directly access port 8091 of Seata Server.
- I know that Seata Server should be deployed in an intranet environment, but in this case, the authentication of Seata Server's port `7091` seems redundant. Docker Images like keycloak, zitadel, and nginx can quickly add authentication functions to Seata Server's port `7091`.
- A potential understanding is that the docker imager of the seata server should allow the passing of environment variables like `SEATA_SERVER_SECRET_TOKEN="yourStrongPassword123!"`, and the configuration file `registry.conf` of the seata client allows the setting of content like `seata.server.secret_token="yourStrongPassword123!"`. To ensure communication security, Seata Server may also support the generation of self-signed TLS certificates or custom TLS certificates.
- Or another possibility is to support JVM arguments like Zookeeper Server does which reads JAAS `java.security.auth.login.config`. Like https://shardingsphere.apache.org/elasticjob/current/cn/user-manual/configuration/external-integration/sasl/ does.
```yaml
services:
  zookeeper-test:
    image: zookeeper:3.9.2
    volumes:
      - ./jaas-server-test.conf:/jaas-test.conf
    environment:
      JVMFLAGS: "-Djava.security.auth.login.config=/jaas-test.conf"
      ZOO_CFG_EXTRA: "authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider sessionRequireClientSASLAuth=true"
    ports:
      - "2181:2181"
```
```
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_bob="bobsecret";
};
```
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

- https://github.com/apache/incubator-seata/wiki/20240427/57e39735794787dd5d6a6975ce80421ecde7e6c6 seems to mention this requirement, but I can't find the corresponding PR.
- ![image](https://github.com/user-attachments/assets/4666b742-4ea4-49e0-a7cb-8ee15b8d075f)

- According to multiple CVEs in the history of ElasticSearch, an authentication that does not support the configuration of TLS certificates does not seem to be secure enough.

## Other related information

- Null.
