### ISSUE TITLE
Seata server can't read start properties, Client can't run

### ISSUE THREAD

**Issue by C-L-STARK** [apache/incubator-seata#7053]
Server Version: docker: seataio/seata-server:1.8.0.2
Client Version: 2.2.0

## Server with config: 

```yaml
server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  file:
    path: ${log.home:${user.home}/logs/seata}
console:
  user:
    username: seata
    password: seata
seata:
  security:
    secretKey: fast
    tokenValidityInMilliseconds: 30000000
  config:
    type: zk
    zk:
      server-addr: 172.17.0.3:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
      node-path: /seata/seata.properties
  registry:
    type: zk
    zk:
      cluster: default
      server-addr: 172.17.0.3:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
  server:
    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
    max-commit-retry-timeout: -1
    max-rollback-retry-timeout: -1
    rollback-failed-unlock-enable: false
    enable-check-auth: true
    enable-parallel-request-handle: true
    retry-dead-threshold: 130000
    xaer-nota-retry-timeout: 60000
    enableParallelRequestHandle: true
    recovery:
      committing-retry-period: 1000
      async-committing-retry-period: 1000
      rollbacking-retry-period: 1000
      timeout-retry-period: 1000
    undo:
      log-save-days: 7
      log-delete-period: 86400000
    session:
      branch-async-queue-size: 5000 #branch async remove queue size
      enable-branch-async-remove: false #enable to asynchronous remove branchSession
  store:
    mode: redis
    session:
      mode: redis
    lock:
      mode: redis
    redis:
      mode: single
      database: 0
      min-conn: 10
      max-conn: 100
      password:
      max-total: 100
      query-limit: 1000
      single:
        host: 172.17.0.4
        port: 6379
      sentinel:
        master-name:
        sentinel-hosts:
        sentinel-password:
  transport:
    rpc-tc-request-timeout: 15000
    enable-tc-server-batch-send-response: false
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      boss-thread-size: 1
```

launch docker with -v meet some error in console: 

```shell
config store.session.mode is not existed, return defaultValue null 
config store.mode is not existed, return defaultValue file 
config store.lock.mode is not existed, return defaultValue null 
```

**but this three config was in my config file and mounted success.**

```
-v "/Users/stark/Desktop/workspace/fast-llm/seata-server/application.yml:/seata-server/resources/application.yml"
```

## Client with config

```yaml
seata:
  enabled: true
  application-id: fastx-ai-llm-domains
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  registry:
    type: zk
    zk:
      cluster: default
      server-addr: 127.0.0.1:2181
      connect-timeout: 2000
      session-timeout: 6000
  config:
    type: zk
    zk:
      node-path: /seata/seata.properties
      server-addr: 127.0.0.1:2181
      connect-timeout: 2000
```

**got this**

```
[, ] 2024-12-09 16:47:47,545 ERROR [main] o.a.s.c.r.n.NettyClientChannelManager [NettyClientChannelManager.java:189] Failed to get available servers: service.vgroupMapping.default_tx_group configuration item is required
org.apache.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.default_tx_group configuration item is required
```

## About document

The official documentation seems a bit disorganized, and following it doesn't allow for a quick understanding and use of a great framework like Seata.

use config, registry with`file` was fine, use `zk` ... not work for me.
