### ISSUE TITLE
云原生k8s环境如何注册？

### ISSUE THREAD

**Issue by zouchengli** [apache/incubator-seata#7361]
需求是，我们的产品微服务都是基于Spring Cloud kubernetes开发的，因此注册中心不是Eureka，我看Seata貌似不支持Kubernetes作为注册中心，看了下文档，注册类型有custom，这个custom是指自定义注册实现吗？具体有啥办法自定义集成spring-cloud-starter-kubernetes-fabric8依赖按照eureka代码例子方式去实现呢？另外注册类型默认是file，那么其他spring cloud微服务作为seata client去发现Kubernetes部署中的server呢？

**Comment by dxlance11** [comment]
同问，似乎只有raft集群模式可以实现

**Comment by zouchengli** [comment]
> 同问，似乎只有raft集群模式可以实现

有试验过吗？

**Comment by dxlance11** [comment]
> > 同问，似乎只有raft集群模式可以实现
> 
> 有试验过吗？

试了，可以部署成功，但是客户端注册一直有问题，我没找到原因，seata文档万年不更新，云原生支持也比较差。
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2025-05-26T16:42:44.953+08:00 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [org/apache/seata/spring/boot/autoconfigure/SeataAutoConfiguration.class]: Failed to instantiate [org.apache.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception with message: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:261)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:796)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:600)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1310)
	at org.dxstudio.rate.DxStartApplication.main(DxStartApplication.java:13)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception with message: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 25 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null
	at org.apache.seata.config.ConfigurationCache.lambda$proxy$0(ConfigurationCache.java:88)
	at jdk.proxy2/jdk.proxy2.$Proxy100.getBoolean(Unknown Source)
	at org.apache.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:115)
	at org.apache.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:187)
	at org.apache.seata.spring.boot.autoconfigure.SeataAutoConfiguration.globalTransactionScanner(SeataAutoConfiguration.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 26 common frames omitted

**Comment by dxlance11** [comment]
> > 同问，似乎只有raft集群模式可以实现
> 
> 有试验过吗？

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: seata
data:
  application.yml: |
    server:
      port: 7091
    
    console:
      user:
        username: seata
        password: seata

    spring:
      application:
        name: seata-server

    logging:
      file:
        path: /tmp/seata-logs
      level:
        root: INFO
        io.seata: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

    seata:
      server:
        raft:
          group: default
          server-addr: seata-server-0.seata-server.seata.svc.cluster.local:9091,seata-server-1.seata-server.seata.svc.cluster.local:9091,seata-server-2.seata-server.seata.svc.cluster.local:9091
          snapshot-interval: 600
          apply-batch: 32
          max-append-bufferSize: 262144
          max-replicator-inflight-msgs: 256
          disruptor-buffer-size: 16384
          election-timeout-ms: 1000
          reporter-enabled: false
          reporter-initial-delay: 60
          serialization: jackson
          compressor: none
          sync: true
          username: seata
          password: seata
      config:
        type: file
      registry:
        type: file
      store:
        mode: raft
        file:
          dir: /seata/sessionStore
      security:
        secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
        tokenValidityInMilliseconds: 1800000
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/metadata/v1/**

---
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: seata
  labels:
    app.kubernetes.io/name: seata-server
spec:
  type: ClusterIP
  clusterIP: None  # 设置为Headless Service
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
      name: http
    - port: 7091
      protocol: TCP
      targetPort: 7091
      name: web
    - port: 9091
      protocol: TCP
      targetPort: 9091
      name: raft
  selector:
    app.kubernetes.io/name: seata-server

---
# 创建一个普通Service用于外部访问
apiVersion: v1
kind: Service
metadata:
  name: seata-server-external
  namespace: seata
  labels:
    app.kubernetes.io/name: seata-server
spec:
  type: ClusterIP
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
      name: http
    - port: 7091
      protocol: TCP
      targetPort: 7091
      name: web
  selector:
    app.kubernetes.io/name: seata-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-server
  namespace: seata
  labels:
    app.kubernetes.io/name: seata-server
spec:
  serviceName: seata-server
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/apache/seata-server:2.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SEATA_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
            - name: console
              containerPort: 7091
              protocol: TCP
            - name: raft
              containerPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /seata-server/resources/application.yml
              name: seata-config
              subPath: application.yml
            - name: seata-data
              mountPath: /seata/sessionStore
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
  volumeClaimTemplates:
    - metadata:
        name: seata-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-hostpath
我的部署文档，你可以参考一下

**Comment by zouchengli** [comment]
> > > 同问，似乎只有raft集群模式可以实现
> > 
> > 
> > 有试验过吗？
> 
> 试了，可以部署成功，但是客户端注册一直有问题，我没找到原因，seata文档万年不更新，云原生支持也比较差。 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled. 2025-05-26T16:42:44.953+08:00 ERROR 1 --- [ main] o.s.boot.SpringApplication : Application run failed
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'globalTransactionScanner' defined in class path resource [org/apache/seata/spring/boot/autoconfigure/SeataAutoConfiguration.class]: Failed to instantiate [org.apache.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception with message: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654) at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1330) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:518) at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:261) at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:796) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:600) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:746) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448) at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1321) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1310) at org.dxstudio.rate.DxStartApplication.main(DxStartApplication.java:13) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception with message: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ... 25 common frames omitted Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.seata.config.Configuration.addConfigListener(String, org.apache.seata.config.ConfigurationChangeListener)" because "originalConfiguration" is null at org.apache.seata.config.ConfigurationCache.lambda$proxy$0(ConfigurationCache.java:88) at jdk.proxy2/jdk.proxy2.$Proxy100.getBoolean(Unknown Source) at org.apache.seata.spring.annotation.GlobalTransactionScanner.(GlobalTransactionScanner.java:115) at org.apache.seata.spring.annotation.GlobalTransactionScanner.(GlobalTransactionScanner.java:187) at org.apache.seata.spring.boot.autoconfigure.SeataAutoConfiguration.globalTransactionScanner(SeataAutoConfiguration.java:84) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ... 26 common frames omitted

可以在钉钉群问问这个问题

**Comment by dxlance11** [comment]
> > 同问，似乎只有raft集群模式可以实现
> 
> 有试验过吗？

解决问题了哥们，有几个问题需要注意，2.3.0有

> > 同问，似乎只有raft集群模式可以实现
> 
> 有试验过吗？

兄弟我这测试成功了，发个测试环境的参考给你。注意点：
1.  2.3.0的客户端有bug，服务端可以用2.3.0，客户端用2.2.0
2. k8s部署raft集群时不能使用容器的默认启动命令，要用一个python脚本等待DNS解析，也就是等k8s的service分配好IP后才行。
3. 参考容器启动args参数需要把服务名和namespace信息加上 export SEATA_IP=$(HOST_NAME).seata-server.seata
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: seata
data:
  application.yml: |
    server:
      port: 7091

    spring:
      application:
        name: seata-server

    logging:
      config: classpath:logback-spring.xml
      file:
        path: ${log.home:${user.home}/logs/seata}

    seata:
      server:
        raft:
          group: default
          server-addr: seata-server-0.seata-server.seata:9091,seata-server-1.seata-server.seata:9091,seata-server-2.seata-server.seata:9091
          snapshot-interval: 600
          apply-batch: 32
          max-append-bufferSize: 262144
          max-replicator-inflight-msgs: 256
          disruptor-buffer-size: 16384
          election-timeout-ms: 1000
          reporter-enabled: false
          reporter-initial-delay: 60
          serialization: jackson
          compressor: none
          sync: true
      config:
        type: file
      registry:
        type: file
      store:
        mode: raft
        file:
          dir: /seata/sessionStore
          max-branch-session-size: 16384
          max-global-session-size: 512
          file-write-buffer-cache-size: 16384
          session-reload-read-size: 100
          flush-disk-mode: async
      security:
        secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
        tokenValidityInMilliseconds: 1800000
        ignore:
          urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/metadata/v1/**
---
apiVersion: v1
kind: Service
metadata:
  name: seata-server
  namespace: seata
  labels:
    app.kubernetes.io/name: seata-server
spec:
  type: ClusterIP
  clusterIP: None  # 设置为Headless Service
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 8091
      name: http
    - port: 7091
      protocol: TCP
      targetPort: 7091
      name: web
    - port: 9091
      protocol: TCP
      targetPort: 9091
      name: raft
  selector:
    app.kubernetes.io/name: seata-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seata-server
  namespace: seata
  labels:
    app.kubernetes.io/name: seata-server
spec:
  serviceName: seata-server
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seata-server
    spec:
      containers:
        - name: seata-server
          image: docker.io/apache/seata-server:2.3.0.jdk21
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - '-c'
            - "export SEATA_IP=$(HOST_NAME).seata-server.seata;python3 -c \"\n\nimport time\nimport socket\n\nprint('Waiting $SEATA_IP to be resolved...')\nwhile True:\n\ttry:\n\t\tip = socket.gethostbyname('$SEATA_IP')\n\t\tprint('Resolve $SEATA_IP to', ip)\n\texcept:\n\t\tprint('Cannot resolve $SEATA_IP, wait 2 seconds', flush=True)\n\t\ttime.sleep(2)\n\t\tcontinue\n\texit(0)\n\n\";/bin/bash /seata-server-entrypoint.sh;"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: store.mode
              value: raft
            - name: server.port
              value: '7091'
            - name: server.servicePort
              value: '8091'
            - name: server.raft.serverAddr
              value: seata-server-0.seata-server.seata:9091,seata-server-1.seata-server.seata:9091,seata-server-2.seata-server.seata:9091
            - name: console.user.username
              value: seata
            - name: console.user.password
              value: '123456'
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
            - name: console
              containerPort: 7091
              protocol: TCP
            - name: raft
              containerPort: 9091
              protocol: TCP
          volumeMounts:
            - mountPath: /seata-server/resources/application.yml
              name: seata-config
              subPath: application.yml
            - name: seata-data
              mountPath: /seata/sessionStore
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config
  volumeClaimTemplates:
    - metadata:
        name: seata-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-hostpath
```
