### ISSUE TITLE
istio VS转发，请求丢失url前缀 ，导致404

### ISSUE THREAD

**Issue by heleihelei** [apache/incubator-seata#7458]
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

1. istio VS转发，请求丢失url前缀
2. 不是重复issue 与 <https://github.com/apache/incubator-seata/issues/5346> 有区别
3. 理论所有转发配置的路径前缀都会丢失，例如nginx（未验证）。

### Ⅱ. Describe what happened

使用web url ： http://host.docker.internal/seata/#/transaction/list ， 但是接口请求地址为http://host.docker.internal/api/v1/console/globalSession/query?withBranch=false&pageSize=10&pageNum=1
如图

<img width="1154" alt="Image" src="https://github.com/user-attachments/assets/a2225dce-9d85-4d4b-9e84-f096e1288cde" />

### Ⅵ. Environment

1. 自己编写helm templates ,  deployment.yaml 关键信息如下
```yaml
      containers:
      - env:
        - name: SEATA_PORT
          value: "8091"
        - name: STORE_MODE
          value: file
        image: apache/seata-server:2.3.0
        imagePullPolicy: IfNotPresent
        name: seata-server
        ports:
        - containerPort: 7091
          name: client
        - containerPort: 8091
          name: client-rpc
```
2. VS 转发配置如下
```yaml
  - match:
    - uri:
        prefix: /seata/
    rewrite:
      uri: /
    route:
    - destination:
        host: seata-server.xxx.svc.cluster.local
        port:
          number: 7091
```
